version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: click
    ports:
      - "9000:9000"
      - "8123:8123"
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: qwerty
      CLICKHOUSE_DB: default
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - docker-net

volumes:
  clickhouse_data:

networks:
  docker-net:
    external: true

