TABLE_NAME = "procurement"


column_mapping = {
    "ID_записи": "record_id",
    "Номер_заказа": "order_number",
    "ID_контракта": "contract_id",
    "ID_партии": "batch_id",
    "Дата_заказа": "order_date",
    "Ожидаемая_дата_поставки": "expected_delivery_date",
    "Фактическая_дата_поставки": "actual_delivery_date",
    "Задержка_поставки_дн": "delivery_delay_days",
    "Поставка_вовремя": "delivery_on_time",
    "ID_поставщика": "supplier_id",
    "Поставщик": "supplier_name",
    "Страна_поставщика": "supplier_country",
    "Регион_поставщика": "supplier_region",
    "Склад": "warehouse",
    "Менеджер": "manager",
    "Инкотермс": "incoterms",
    "Категория_товара": "product_category",
    "Подкатегория_товара": "product_subcategory",
    "Код_товара": "product_code",
    "Единица_изм": "unit",
    "Количество": "quantity",
    "Количество_отказано": "quantity_rejected",
    "Количество_принято": "quantity_accepted",
    "Валюта": "currency",
    "Цена_за_ед": "unit_price",
    "Курс_к_руб": "currency_rate_rub",
    "Сумма_руб": "total_cost_rub",
    "Ставка_НДС": "vat_rate",
    "Сумма_НДС": "vat_amount",
    "Сумма_с_НДС_руб": "total_with_vat_rub",
    "Тип_транспорта": "transport_type",
    "Темп_при_доставке_C": "delivery_temp_c",
    "Класс_качества": "quality_class",
    "Доля_брака": "defects_rate",
    "Условия_оплаты": "payment_terms",
    "Статус_оплаты": "payment_status",
    "Статус_согласования": "approval_status",
    "День_недели_заказа": "order_weekday",
    "Месяц_заказа": "order_month",
    "Год_заказа": "order_year",
}